name = "THM Magic Modpack"
author = "ArcOnyx"
version = "0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f8d00b17bbc5d7ab72f24d8938bf8205fff3840d793e883b1b95b14d58cd5ca"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
