name = "THM Magic Modpack"
author = "ArcOnyx"
version = "0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65dbf374a31076ab5daa16c474107a1a6ac1bca9089ddc7e16b6351d763db8e4"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
