name = "THM Magic Modpack"
author = "ArcOnyx"
version = "0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a53c4fb582c4be996ae8cb0fe72da6da68cf92756276f86f3f69719a31a8d6c"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
